"""Generates version_info.txt -- the Windows EXE version-resource file
PyInstaller embeds (see telegram_mass_sender.spec's EXE(..., version=...)),
shown in Windows Explorer's file Properties > Details tab.

Run before every build (build_windows.bat does this automatically) rather
than hand-maintaining version_info.txt as a static file: app.version.APP_VERSION
is this project's one source of truth for the version string, and
PyInstaller's version file format only accepts a single eval()'d Python
expression (see PyInstaller.utils.win32.versioninfo.load_version_info_from_text_file),
which rules out a plain `from app.version import APP_VERSION` inside the
file itself -- generating it here instead keeps the two from drifting
apart without duplicating the version number by hand at every release.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.version import APP_VERSION

_OUTPUT_PATH = Path(__file__).resolve().parent.parent / "version_info.txt"

_TEMPLATE = """# UTF-8
#
# Auto-generated by scripts/generate_version_info.py from app.version.APP_VERSION --
# do not edit by hand, it will be overwritten on the next build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, 0),
    prodvers=({major}, {minor}, {patch}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'BagroDeRose'),
        StringStruct(u'FileDescription', u'Telegram Mass Sender'),
        StringStruct(u'FileVersion', u'{version}'),
        StringStruct(u'InternalName', u'TelegramMassSender'),
        StringStruct(u'LegalCopyright', u'\\xa9 BagroDeRose'),
        StringStruct(u'OriginalFilename', u'TelegramMassSender.exe'),
        StringStruct(u'ProductName', u'Telegram Mass Sender'),
        StringStruct(u'ProductVersion', u'{version}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def build_version_info_text(app_version: str) -> str:
    parts = app_version.split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise ValueError(f"APP_VERSION must be MAJOR.MINOR.PATCH (got {app_version!r})")
    major, minor, patch = parts
    return _TEMPLATE.format(major=major, minor=minor, patch=patch, version=app_version)


def main() -> None:
    text = build_version_info_text(APP_VERSION)
    _OUTPUT_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {_OUTPUT_PATH} for version {APP_VERSION}")


if __name__ == "__main__":
    main()
